# Generated by Django 2.1.2 on 2018-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0002_auto_20181006_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
