# Generated by Django 2.1.2 on 2018-10-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share_api', '0005_auto_20181006_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
    ]
